# Generated by Django 4.2.3 on 2023-12-14 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_alter_cart_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartelement',
            name='image',
            field=models.CharField(default='', max_length=70),
        ),
    ]
