# Generated by Django 4.2.3 on 2023-10-19 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_category_slug_alter_category_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='createdDate',
            field=models.DateField(auto_now_add=True),
        ),
    ]
