# Generated by Django 4.2.3 on 2023-10-25 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_product_createddate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='seller',
            new_name='seller_id',
        ),
    ]
