# Generated by Django 4.2.3 on 2023-10-26 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_rename_seller_product_seller_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='edition',
            field=models.CharField(default='Normal', max_length=50),
        ),
    ]
