from .test_product_detail_view import ProductDetailViewTest
from .test_product_create_view import ProductCreateViewTest
from .test_add_product_categories import AddProductCategoriesViewTest
from .test_load_category import LoadCategoryViewTest