FROM python:3.11

RUN mkdir -p /app/letsencrypt/
RUN mkdir -p /app/static/

WORKDIR /app
COPY ./requirements.txt /app/requirements.txt
RUN pip install -r requirements.txt
COPY . /app

EXPOSE 8000

# Collect static files

CMD ["gunicorn", "--bind", "0.0.0.0:8000", "--access-logfile", "/app/access.log", "--keyfile", "/app/letsencrypt/live/gaminspot.games/privkey.pem", "--certfile", "/app/letsencrypt/live/gaminspot.games/cert.pem", "Gaminspot.wsgi:application"]