# Generated by Django 4.2.3 on 2023-08-23 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='userId',
            new_name='id',
        ),
    ]
