name: Deploy to Production

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create SSH directory
        run: mkdir -p ~/.ssh

      - name: Set up known_hosts
        run: ssh-keyscan -t rsa 35.196.242.162 >> ~/.ssh/known_hosts

      - name: Debug Known Hosts
        run: cat ~/.ssh/known_hosts

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: Deploy to VPS
        run: ssh -tt -o StrictHostKeyChecking=no githubuser@35.196.242.162 'touch /home/githubuser/test.txt'
