name: Deploy to Production

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create SSH directory
        run: mkdir -p ~/.ssh

      - name: Set up known_hosts
        run: ssh-keyscan -t rsa 35.196.242.162 >> ~/.ssh/known_hosts

      - name: Debug Known Hosts
        run: cat ~/.ssh/known_hosts

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: Deploy to VPS
        run: |
          ssh githubuser@35.196.242.162 'cd /var/www/html &&
          sudo cp Gam-In-Spot/back/db.sqlite3 backup/ &&
          cd Gam-In-Spot &&
          sudo git stash &&
          sudo git pull &&
          sudo docker-compose down &&
          sudo docker image rm gam-in-spot-gaminspot-front &&
          cd .. &&
          sudo cp backup/front/.env Gam-In-Spot/front &&
          sudo cp backup/back/.env Gam-In-Spot/back &&
          sudo cp backup/db.sqlite3 Gam-In-Spot/back && 
          cd Gam-In-Spot/front &&
          sudo docker build -t gam-in-spot-gaminspot-front . &&
          cd .. &&
          sudo docker-compose up -d &&
          sudo docker cp ../backup/letsencrypt gam-in-spot-gaminspot-front-1:/etc/ &&
          sudo docker cp ../backup/letsencrypt gam-in-spot-gaminspot-back-1:/app/ &&
          sudo docker cp ../backup/nginx.conf gam-in-spot-gaminspot-front-1:/etc/nginx/nginx.conf &&
          cd Gam-In-Spot &&
          sudo docker-compose restart'

# jobs:
#   deploy:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v2

#       - name: Set up Google Cloud SDK
#         uses: google-github-actions/auth@v2
#         with:
#           credentials_json: ${{ secrets.GCLOUD_SERVICE_KEY }}

#       - name: SSH into VM
#         uses: google-github-actions/ssh-compute@v1
#         with:
#           instance_name: "container-gaminspot"
#           zone: "us-east1-b"
#           ssh_private_key: "${{ secrets.SSH_KEY }}"
#           command: "echo Hello world --troubleshoot"

# - name: Move to /var/www/html directory
#   run: |
#     cd /var/www/html
#     hostname

# - name: Copy db.sqlite3 to backup directory
#   run: sudo cp Gam-In-Spot/back/db.sqlite3 backup/

# - name: Move to Gam-In-Spot directory
#   run: cd Gam-In-Spot

# - name: Stash uncommitted changes
#   run: sudo git stash

# - name: Update code from Git repository
#   run: sudo git pull

# - name: Stop Docker container
#   run: sudo docker-compose down

# - name: Remove Docker image
#   run: sudo docker image rm gam-in-spot-gaminspot-front

# - name: Move back to previous directory
#   run: cd ..

# - name: Copy .env and db.sqlite3 from backup to Gam-In-Spot
#   run: |
#     sudo cp backup/front/.env Gam-In-Spot/front
#     sudo cp backup/back/.env Gam-In-Spot/back
#     sudo cp backup/db.sqlite3 Gam-In-Spot/back

# - name: Move to Gam-In-Spot/front directory
#   run: cd Gam-In-Spot/front

# - name: Build Docker image gam-in-spot-gaminspot-front
#   run: sudo docker build -t gam-in-spot-gaminspot-front .

# - name: Move back to previous directory
#   run: cd ..

# - name: Launch Docker containers
#   run: sudo docker-compose up -d

# - name: Copy files from backup to containers
#   run: |
#     sudo docker cp ../backup/letsencrypt gam-in-spot-gaminspot-front-1:/etc/
#     sudo docker cp ../backup/letsencrypt gam-in-spot-gaminspot-back-1:/app/
#     sudo docker cp ../backup/nginx.conf gam-in-spot-gaminspot-front-1:/etc/nginx/nginx.conf

# - name: Restart Docker containers
#   run: |
#     cd Gam-In-Spot
#     sudo docker-compose restart
